// <auto-generated />
namespace TeamRoles.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Assignmentsonetomany : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Assignmentsonetomany));
        
        string IMigrationMetadata.Id
        {
            get { return "201903250913520_Assignments-one-to-many"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
